/*
 * investor
 * This swagger documentation provides investor onboarding api details.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.investor.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** Address */
@JsonPropertyOrder({
  Address.JSON_PROPERTY_ADDRESS_LINE1,
  Address.JSON_PROPERTY_ADDRESS_LINE2,
  Address.JSON_PROPERTY_LANDMARK,
  Address.JSON_PROPERTY_CITY,
  Address.JSON_PROPERTY_POSTAL_CODE,
  Address.JSON_PROPERTY_STATE_OR_PROVINCE,
  Address.JSON_PROPERTY_COUNTRY
})
@JsonTypeName("Address")
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2020-10-03T17:43:44.473+05:30[Asia/Kolkata]")
public class Address {
  public static final String JSON_PROPERTY_ADDRESS_LINE1 = "addressLine1";
  private String addressLine1;

  public static final String JSON_PROPERTY_ADDRESS_LINE2 = "addressLine2";
  private String addressLine2;

  public static final String JSON_PROPERTY_LANDMARK = "landmark";
  private String landmark;

  public static final String JSON_PROPERTY_CITY = "city";
  private String city;

  public static final String JSON_PROPERTY_POSTAL_CODE = "postalCode";
  private String postalCode;

  public static final String JSON_PROPERTY_STATE_OR_PROVINCE = "stateOrProvince";
  private String stateOrProvince;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private Country country;

  public Address addressLine1(String addressLine1) {

    this.addressLine1 = addressLine1;
    return this;
  }

  /**
   * Get addressLine1
   *
   * @return addressLine1
   */
  @javax.annotation.Nullable
  @ApiModelProperty(example = "123,", value = "")
  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAddressLine1() {
    return addressLine1;
  }

  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }

  public Address addressLine2(String addressLine2) {

    this.addressLine2 = addressLine2;
    return this;
  }

  /**
   * Get addressLine2
   *
   * @return addressLine2
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAddressLine2() {
    return addressLine2;
  }

  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }

  public Address landmark(String landmark) {

    this.landmark = landmark;
    return this;
  }

  /**
   * Get landmark
   *
   * @return landmark
   */
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Ahmedabad", value = "")
  @JsonProperty(JSON_PROPERTY_LANDMARK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLandmark() {
    return landmark;
  }

  public void setLandmark(String landmark) {
    this.landmark = landmark;
  }

  public Address city(String city) {

    this.city = city;
    return this;
  }

  /**
   * Get city
   *
   * @return city
   */
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Ahmedabad", value = "")
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public Address postalCode(String postalCode) {

    this.postalCode = postalCode;
    return this;
  }

  /**
   * Get postalCode
   *
   * @return postalCode
   */
  @javax.annotation.Nullable
  @ApiModelProperty(example = "500081", value = "")
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public Address stateOrProvince(String stateOrProvince) {

    this.stateOrProvince = stateOrProvince;
    return this;
  }

  /**
   * Get stateOrProvince
   *
   * @return stateOrProvince
   */
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Guj", value = "")
  @JsonProperty(JSON_PROPERTY_STATE_OR_PROVINCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStateOrProvince() {
    return stateOrProvince;
  }

  public void setStateOrProvince(String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
  }

  public Address country(Country country) {

    this.country = country;
    return this;
  }

  /**
   * Get country
   *
   * @return country
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Country getCountry() {
    return country;
  }

  public void setCountry(Country country) {
    this.country = country;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return Objects.equals(this.addressLine1, address.addressLine1)
        && Objects.equals(this.addressLine2, address.addressLine2)
        && Objects.equals(this.landmark, address.landmark)
        && Objects.equals(this.city, address.city)
        && Objects.equals(this.postalCode, address.postalCode)
        && Objects.equals(this.stateOrProvince, address.stateOrProvince)
        && Objects.equals(this.country, address.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        addressLine1, addressLine2, landmark, city, postalCode, stateOrProvince, country);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    landmark: ").append(toIndentedString(landmark)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    stateOrProvince: ").append(toIndentedString(stateOrProvince)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
