/*
 * investor
 * This swagger documentation provides investor onboarding api details.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.investor.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** ContactDetails */
@JsonPropertyOrder({
  ContactDetails.JSON_PROPERTY_NAME,
  ContactDetails.JSON_PROPERTY_ADDRESS,
  ContactDetails.JSON_PROPERTY_PRIMARY_PHONE_NUMBER,
  ContactDetails.JSON_PROPERTY_SECONDARY_PHONE_NUMBER,
  ContactDetails.JSON_PROPERTY_EMAIL
})
@JsonTypeName("ContactDetails")
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2020-10-03T17:43:44.473+05:30[Asia/Kolkata]")
public class ContactDetails {
  public static final String JSON_PROPERTY_NAME = "name";
  private Name name;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private Address address;

  public static final String JSON_PROPERTY_PRIMARY_PHONE_NUMBER = "primaryPhoneNumber";
  private PhoneNumber primaryPhoneNumber;

  public static final String JSON_PROPERTY_SECONDARY_PHONE_NUMBER = "secondaryPhoneNumber";
  private PhoneNumber secondaryPhoneNumber;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public ContactDetails name(Name name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Name getName() {
    return name;
  }

  public void setName(Name name) {
    this.name = name;
  }

  public ContactDetails address(Address address) {

    this.address = address;
    return this;
  }

  /**
   * Get address
   *
   * @return address
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public ContactDetails primaryPhoneNumber(PhoneNumber primaryPhoneNumber) {

    this.primaryPhoneNumber = primaryPhoneNumber;
    return this;
  }

  /**
   * Get primaryPhoneNumber
   *
   * @return primaryPhoneNumber
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRIMARY_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PhoneNumber getPrimaryPhoneNumber() {
    return primaryPhoneNumber;
  }

  public void setPrimaryPhoneNumber(PhoneNumber primaryPhoneNumber) {
    this.primaryPhoneNumber = primaryPhoneNumber;
  }

  public ContactDetails secondaryPhoneNumber(PhoneNumber secondaryPhoneNumber) {

    this.secondaryPhoneNumber = secondaryPhoneNumber;
    return this;
  }

  /**
   * Get secondaryPhoneNumber
   *
   * @return secondaryPhoneNumber
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SECONDARY_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PhoneNumber getSecondaryPhoneNumber() {
    return secondaryPhoneNumber;
  }

  public void setSecondaryPhoneNumber(PhoneNumber secondaryPhoneNumber) {
    this.secondaryPhoneNumber = secondaryPhoneNumber;
  }

  public ContactDetails email(String email) {

    this.email = email;
    return this;
  }

  /**
   * Get email
   *
   * @return email
   */
  @javax.annotation.Nullable
  @ApiModelProperty(example = "vinay91098@gmail.com", value = "")
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactDetails contactDetails = (ContactDetails) o;
    return Objects.equals(this.name, contactDetails.name)
        && Objects.equals(this.address, contactDetails.address)
        && Objects.equals(this.primaryPhoneNumber, contactDetails.primaryPhoneNumber)
        && Objects.equals(this.secondaryPhoneNumber, contactDetails.secondaryPhoneNumber)
        && Objects.equals(this.email, contactDetails.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, address, primaryPhoneNumber, secondaryPhoneNumber, email);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactDetails {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    primaryPhoneNumber: ").append(toIndentedString(primaryPhoneNumber)).append("\n");
    sb.append("    secondaryPhoneNumber: ")
        .append(toIndentedString(secondaryPhoneNumber))
        .append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
