/*
 * investor
 * This swagger documentation provides investor onboarding api details.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.investor.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/** Investor */
@JsonPropertyOrder({
  Investor.JSON_PROPERTY_INVESTOR_ID,
  Investor.JSON_PROPERTY_NAME,
  Investor.JSON_PROPERTY_PHOTO,
  Investor.JSON_PROPERTY_STOCK_VALUE,
  Investor.JSON_PROPERTY_STOCK_ID,
  Investor.JSON_PROPERTY_STOCK_TYPE,
  Investor.JSON_PROPERTY_CONTACT_DETAILS,
  Investor.JSON_PROPERTY_INVESTOR_DOCUMENTS
})
@JsonTypeName("investor")
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2020-10-03T17:43:44.473+05:30[Asia/Kolkata]")
public class Investor {
  public static final String JSON_PROPERTY_INVESTOR_ID = "investorId";
  private String investorId;

  public static final String JSON_PROPERTY_NAME = "name";
  private Name name;

  public static final String JSON_PROPERTY_PHOTO = "photo";
  private String photo;

  public static final String JSON_PROPERTY_STOCK_VALUE = "stockValue";
  private List<StockValue> stockValue = null;

  public static final String JSON_PROPERTY_STOCK_ID = "stockId";
  private UUID stockId;

  public static final String JSON_PROPERTY_STOCK_TYPE = "stockType";
  private StockType stockType;

  public static final String JSON_PROPERTY_CONTACT_DETAILS = "contactDetails";
  private ContactDetails contactDetails;

  public static final String JSON_PROPERTY_INVESTOR_DOCUMENTS = "investorDocuments";
  private List<DocumentRequest> investorDocuments = null;

  public Investor investorId(String investorId) {

    this.investorId = investorId;
    return this;
  }

  /**
   * generated investor Id
   *
   * @return investorId
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "generated investor Id")
  @JsonProperty(JSON_PROPERTY_INVESTOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInvestorId() {
    return investorId;
  }

  public void setInvestorId(String investorId) {
    this.investorId = investorId;
  }

  public Investor name(Name name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Name getName() {
    return name;
  }

  public void setName(Name name) {
    this.name = name;
  }

  public Investor photo(String photo) {

    this.photo = photo;
    return this;
  }

  /**
   * investor picture (PII Data)
   *
   * @return photo
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "investor picture (PII Data)")
  @JsonProperty(JSON_PROPERTY_PHOTO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPhoto() {
    return photo;
  }

  public void setPhoto(String photo) {
    this.photo = photo;
  }

  public Investor stockValue(List<StockValue> stockValue) {

    this.stockValue = stockValue;
    return this;
  }

  public Investor addStockValueItem(StockValue stockValueItem) {
    if (this.stockValue == null) {
      this.stockValue = new ArrayList<StockValue>();
    }
    this.stockValue.add(stockValueItem);
    return this;
  }

  /**
   * Get stockValue
   *
   * @return stockValue
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STOCK_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<StockValue> getStockValue() {
    return stockValue;
  }

  public void setStockValue(List<StockValue> stockValue) {
    this.stockValue = stockValue;
  }

  public Investor stockId(UUID stockId) {

    this.stockId = stockId;
    return this;
  }

  /**
   * Get stockId
   *
   * @return stockId
   */
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STOCK_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getStockId() {
    return stockId;
  }

  public void setStockId(UUID stockId) {
    this.stockId = stockId;
  }

  public Investor stockType(StockType stockType) {

    this.stockType = stockType;
    return this;
  }

  /**
   * Get stockType
   *
   * @return stockType
   */
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STOCK_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StockType getStockType() {
    return stockType;
  }

  public void setStockType(StockType stockType) {
    this.stockType = stockType;
  }

  public Investor contactDetails(ContactDetails contactDetails) {

    this.contactDetails = contactDetails;
    return this;
  }

  /**
   * Get contactDetails
   *
   * @return contactDetails
   */
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONTACT_DETAILS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ContactDetails getContactDetails() {
    return contactDetails;
  }

  public void setContactDetails(ContactDetails contactDetails) {
    this.contactDetails = contactDetails;
  }

  public Investor investorDocuments(List<DocumentRequest> investorDocuments) {

    this.investorDocuments = investorDocuments;
    return this;
  }

  public Investor addInvestorDocumentsItem(DocumentRequest investorDocumentsItem) {
    if (this.investorDocuments == null) {
      this.investorDocuments = new ArrayList<DocumentRequest>();
    }
    this.investorDocuments.add(investorDocumentsItem);
    return this;
  }

  /**
   * Get investorDocuments
   *
   * @return investorDocuments
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INVESTOR_DOCUMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<DocumentRequest> getInvestorDocuments() {
    return investorDocuments;
  }

  public void setInvestorDocuments(List<DocumentRequest> investorDocuments) {
    this.investorDocuments = investorDocuments;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Investor investor = (Investor) o;
    return Objects.equals(this.investorId, investor.investorId)
        && Objects.equals(this.name, investor.name)
        && Objects.equals(this.photo, investor.photo)
        && Objects.equals(this.stockValue, investor.stockValue)
        && Objects.equals(this.stockId, investor.stockId)
        && Objects.equals(this.stockType, investor.stockType)
        && Objects.equals(this.contactDetails, investor.contactDetails)
        && Objects.equals(this.investorDocuments, investor.investorDocuments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        investorId, name, photo, stockValue, stockId, stockType, contactDetails, investorDocuments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Investor {\n");
    sb.append("    investorId: ").append(toIndentedString(investorId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    photo: ").append(toIndentedString(photo)).append("\n");
    sb.append("    stockValue: ").append(toIndentedString(stockValue)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    stockType: ").append(toIndentedString(stockType)).append("\n");
    sb.append("    contactDetails: ").append(toIndentedString(contactDetails)).append("\n");
    sb.append("    investorDocuments: ").append(toIndentedString(investorDocuments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
