/*
 * investor
 * This swagger documentation provides investor onboarding api details.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.investor.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/** InvestorUpdateRequest */
@JsonPropertyOrder({
  InvestorUpdateRequest.JSON_PROPERTY_INVESTOR_ID,
  InvestorUpdateRequest.JSON_PROPERTY_NAME,
  InvestorUpdateRequest.JSON_PROPERTY_PHOTO,
  InvestorUpdateRequest.JSON_PROPERTY_STOCK_ID,
  InvestorUpdateRequest.JSON_PROPERTY_STOCK_VALUE,
  InvestorUpdateRequest.JSON_PROPERTY_STOCK_TYPE,
  InvestorUpdateRequest.JSON_PROPERTY_CONTACT_DETAILS,
  InvestorUpdateRequest.JSON_PROPERTY_INVESTOR_DOCUMENTS,
  InvestorUpdateRequest.JSON_PROPERTY_IS_ACTIVE,
  InvestorUpdateRequest.JSON_PROPERTY_IS_VERIFIED,
  InvestorUpdateRequest.JSON_PROPERTY_IS_DELETED
})
@JsonTypeName("InvestorUpdateRequest")
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2020-10-03T17:43:44.473+05:30[Asia/Kolkata]")
public class InvestorUpdateRequest {
  public static final String JSON_PROPERTY_INVESTOR_ID = "investorId";
  private String investorId;

  public static final String JSON_PROPERTY_NAME = "name";
  private Name name;

  public static final String JSON_PROPERTY_PHOTO = "photo";
  private String photo;

  public static final String JSON_PROPERTY_STOCK_ID = "stockId";
  private UUID stockId;

  public static final String JSON_PROPERTY_STOCK_VALUE = "stockValue";
  private List<StockValue> stockValue = null;

  public static final String JSON_PROPERTY_STOCK_TYPE = "stockType";
  private StockType stockType;

  public static final String JSON_PROPERTY_CONTACT_DETAILS = "contactDetails";
  private ContactDetails contactDetails;

  public static final String JSON_PROPERTY_INVESTOR_DOCUMENTS = "investorDocuments";
  private List<DocumentRequest> investorDocuments = null;

  public static final String JSON_PROPERTY_IS_ACTIVE = "isActive";
  private Boolean isActive;

  public static final String JSON_PROPERTY_IS_VERIFIED = "isVerified";
  private Boolean isVerified;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  private Boolean isDeleted;

  public InvestorUpdateRequest investorId(String investorId) {

    this.investorId = investorId;
    return this;
  }

  /**
   * generated unique investor Id
   *
   * @return investorId
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "generated unique investor Id")
  @JsonProperty(JSON_PROPERTY_INVESTOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInvestorId() {
    return investorId;
  }

  public void setInvestorId(String investorId) {
    this.investorId = investorId;
  }

  public InvestorUpdateRequest name(Name name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Name getName() {
    return name;
  }

  public void setName(Name name) {
    this.name = name;
  }

  public InvestorUpdateRequest photo(String photo) {

    this.photo = photo;
    return this;
  }

  /**
   * investor picture (PII Data)
   *
   * @return photo
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "investor picture (PII Data)")
  @JsonProperty(JSON_PROPERTY_PHOTO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPhoto() {
    return photo;
  }

  public void setPhoto(String photo) {
    this.photo = photo;
  }

  public InvestorUpdateRequest stockId(UUID stockId) {

    this.stockId = stockId;
    return this;
  }

  /**
   * Get stockId
   *
   * @return stockId
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STOCK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getStockId() {
    return stockId;
  }

  public void setStockId(UUID stockId) {
    this.stockId = stockId;
  }

  public InvestorUpdateRequest stockValue(List<StockValue> stockValue) {

    this.stockValue = stockValue;
    return this;
  }

  public InvestorUpdateRequest addStockValueItem(StockValue stockValueItem) {
    if (this.stockValue == null) {
      this.stockValue = new ArrayList<StockValue>();
    }
    this.stockValue.add(stockValueItem);
    return this;
  }

  /**
   * Get stockValue
   *
   * @return stockValue
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STOCK_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<StockValue> getStockValue() {
    return stockValue;
  }

  public void setStockValue(List<StockValue> stockValue) {
    this.stockValue = stockValue;
  }

  public InvestorUpdateRequest stockType(StockType stockType) {

    this.stockType = stockType;
    return this;
  }

  /**
   * Get stockType
   *
   * @return stockType
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STOCK_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StockType getStockType() {
    return stockType;
  }

  public void setStockType(StockType stockType) {
    this.stockType = stockType;
  }

  public InvestorUpdateRequest contactDetails(ContactDetails contactDetails) {

    this.contactDetails = contactDetails;
    return this;
  }

  /**
   * Get contactDetails
   *
   * @return contactDetails
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTACT_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ContactDetails getContactDetails() {
    return contactDetails;
  }

  public void setContactDetails(ContactDetails contactDetails) {
    this.contactDetails = contactDetails;
  }

  public InvestorUpdateRequest investorDocuments(List<DocumentRequest> investorDocuments) {

    this.investorDocuments = investorDocuments;
    return this;
  }

  public InvestorUpdateRequest addInvestorDocumentsItem(DocumentRequest investorDocumentsItem) {
    if (this.investorDocuments == null) {
      this.investorDocuments = new ArrayList<DocumentRequest>();
    }
    this.investorDocuments.add(investorDocumentsItem);
    return this;
  }

  /**
   * Get investorDocuments
   *
   * @return investorDocuments
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INVESTOR_DOCUMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<DocumentRequest> getInvestorDocuments() {
    return investorDocuments;
  }

  public void setInvestorDocuments(List<DocumentRequest> investorDocuments) {
    this.investorDocuments = investorDocuments;
  }

  public InvestorUpdateRequest isActive(Boolean isActive) {

    this.isActive = isActive;
    return this;
  }

  /**
   * Get isActive
   *
   * @return isActive
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public InvestorUpdateRequest isVerified(Boolean isVerified) {

    this.isVerified = isVerified;
    return this;
  }

  /**
   * Get isVerified
   *
   * @return isVerified
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsVerified() {
    return isVerified;
  }

  public void setIsVerified(Boolean isVerified) {
    this.isVerified = isVerified;
  }

  public InvestorUpdateRequest isDeleted(Boolean isDeleted) {

    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   *
   * @return isDeleted
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvestorUpdateRequest investorUpdateRequest = (InvestorUpdateRequest) o;
    return Objects.equals(this.investorId, investorUpdateRequest.investorId)
        && Objects.equals(this.name, investorUpdateRequest.name)
        && Objects.equals(this.photo, investorUpdateRequest.photo)
        && Objects.equals(this.stockId, investorUpdateRequest.stockId)
        && Objects.equals(this.stockValue, investorUpdateRequest.stockValue)
        && Objects.equals(this.stockType, investorUpdateRequest.stockType)
        && Objects.equals(this.contactDetails, investorUpdateRequest.contactDetails)
        && Objects.equals(this.investorDocuments, investorUpdateRequest.investorDocuments)
        && Objects.equals(this.isActive, investorUpdateRequest.isActive)
        && Objects.equals(this.isVerified, investorUpdateRequest.isVerified)
        && Objects.equals(this.isDeleted, investorUpdateRequest.isDeleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        investorId,
        name,
        photo,
        stockId,
        stockValue,
        stockType,
        contactDetails,
        investorDocuments,
        isActive,
        isVerified,
        isDeleted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvestorUpdateRequest {\n");
    sb.append("    investorId: ").append(toIndentedString(investorId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    photo: ").append(toIndentedString(photo)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    stockValue: ").append(toIndentedString(stockValue)).append("\n");
    sb.append("    stockType: ").append(toIndentedString(stockType)).append("\n");
    sb.append("    contactDetails: ").append(toIndentedString(contactDetails)).append("\n");
    sb.append("    investorDocuments: ").append(toIndentedString(investorDocuments)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    isVerified: ").append(toIndentedString(isVerified)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
