/*
 * investor
 * This swagger documentation provides investor onboarding api details.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.investor.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/** InvestorResponse */
@JsonPropertyOrder({
  InvestorResponse.JSON_PROPERTY_MARKET_ID,
  InvestorResponse.JSON_PROPERTY_INVESTOR_ID,
  InvestorResponse.JSON_PROPERTY_NAME,
  InvestorResponse.JSON_PROPERTY_STOCK_ID,
  InvestorResponse.JSON_PROPERTY_STOCK_VALUE,
  InvestorResponse.JSON_PROPERTY_STOCK_TYPE,
  InvestorResponse.JSON_PROPERTY_PII_RECORD_ID,
  InvestorResponse.JSON_PROPERTY_IS_ACTIVE,
  InvestorResponse.JSON_PROPERTY_IS_VERIFIED,
  InvestorResponse.JSON_PROPERTY_IS_DELETED
})
@JsonTypeName("InvestorResponse")
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2020-10-03T17:43:44.473+05:30[Asia/Kolkata]")
public class InvestorResponse {
  public static final String JSON_PROPERTY_MARKET_ID = "marketId";
  private UUID marketId;

  public static final String JSON_PROPERTY_INVESTOR_ID = "investorId";
  private String investorId;

  public static final String JSON_PROPERTY_NAME = "name";
  private Name name;

  public static final String JSON_PROPERTY_STOCK_ID = "stockId";
  private UUID stockId;

  public static final String JSON_PROPERTY_STOCK_VALUE = "stockValue";
  private List<StockValue> stockValue = null;

  public static final String JSON_PROPERTY_STOCK_TYPE = "stockType";
  private StockType stockType;

  public static final String JSON_PROPERTY_PII_RECORD_ID = "piiRecordId";
  private UUID piiRecordId;

  public static final String JSON_PROPERTY_IS_ACTIVE = "isActive";
  private Boolean isActive;

  public static final String JSON_PROPERTY_IS_VERIFIED = "isVerified";
  private Boolean isVerified;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  private Boolean isDeleted;

  public InvestorResponse marketId(UUID marketId) {

    this.marketId = marketId;
    return this;
  }

  /**
   * Get marketId
   *
   * @return marketId
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MARKET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getMarketId() {
    return marketId;
  }

  public void setMarketId(UUID marketId) {
    this.marketId = marketId;
  }

  public InvestorResponse investorId(String investorId) {

    this.investorId = investorId;
    return this;
  }

  /**
   * generated investor Id
   *
   * @return investorId
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "generated investor Id")
  @JsonProperty(JSON_PROPERTY_INVESTOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInvestorId() {
    return investorId;
  }

  public void setInvestorId(String investorId) {
    this.investorId = investorId;
  }

  public InvestorResponse name(Name name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Name getName() {
    return name;
  }

  public void setName(Name name) {
    this.name = name;
  }

  public InvestorResponse stockId(UUID stockId) {

    this.stockId = stockId;
    return this;
  }

  /**
   * Get stockId
   *
   * @return stockId
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STOCK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getStockId() {
    return stockId;
  }

  public void setStockId(UUID stockId) {
    this.stockId = stockId;
  }

  public InvestorResponse stockValue(List<StockValue> stockValue) {

    this.stockValue = stockValue;
    return this;
  }

  public InvestorResponse addStockValueItem(StockValue stockValueItem) {
    if (this.stockValue == null) {
      this.stockValue = new ArrayList<StockValue>();
    }
    this.stockValue.add(stockValueItem);
    return this;
  }

  /**
   * Get stockValue
   *
   * @return stockValue
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STOCK_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<StockValue> getStockValue() {
    return stockValue;
  }

  public void setStockValue(List<StockValue> stockValue) {
    this.stockValue = stockValue;
  }

  public InvestorResponse stockType(StockType stockType) {

    this.stockType = stockType;
    return this;
  }

  /**
   * Get stockType
   *
   * @return stockType
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STOCK_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StockType getStockType() {
    return stockType;
  }

  public void setStockType(StockType stockType) {
    this.stockType = stockType;
  }

  public InvestorResponse piiRecordId(UUID piiRecordId) {

    this.piiRecordId = piiRecordId;
    return this;
  }

  /**
   * Get piiRecordId
   *
   * @return piiRecordId
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PII_RECORD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getPiiRecordId() {
    return piiRecordId;
  }

  public void setPiiRecordId(UUID piiRecordId) {
    this.piiRecordId = piiRecordId;
  }

  public InvestorResponse isActive(Boolean isActive) {

    this.isActive = isActive;
    return this;
  }

  /**
   * Get isActive
   *
   * @return isActive
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public InvestorResponse isVerified(Boolean isVerified) {

    this.isVerified = isVerified;
    return this;
  }

  /**
   * Get isVerified
   *
   * @return isVerified
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsVerified() {
    return isVerified;
  }

  public void setIsVerified(Boolean isVerified) {
    this.isVerified = isVerified;
  }

  public InvestorResponse isDeleted(Boolean isDeleted) {

    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   *
   * @return isDeleted
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvestorResponse investorResponse = (InvestorResponse) o;
    return Objects.equals(this.marketId, investorResponse.marketId)
        && Objects.equals(this.investorId, investorResponse.investorId)
        && Objects.equals(this.name, investorResponse.name)
        && Objects.equals(this.stockId, investorResponse.stockId)
        && Objects.equals(this.stockValue, investorResponse.stockValue)
        && Objects.equals(this.stockType, investorResponse.stockType)
        && Objects.equals(this.piiRecordId, investorResponse.piiRecordId)
        && Objects.equals(this.isActive, investorResponse.isActive)
        && Objects.equals(this.isVerified, investorResponse.isVerified)
        && Objects.equals(this.isDeleted, investorResponse.isDeleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        marketId,
        investorId,
        name,
        stockId,
        stockValue,
        stockType,
        piiRecordId,
        isActive,
        isVerified,
        isDeleted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvestorResponse {\n");
    sb.append("    marketId: ").append(toIndentedString(marketId)).append("\n");
    sb.append("    investorId: ").append(toIndentedString(investorId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    stockValue: ").append(toIndentedString(stockValue)).append("\n");
    sb.append("    stockType: ").append(toIndentedString(stockType)).append("\n");
    sb.append("    piiRecordId: ").append(toIndentedString(piiRecordId)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    isVerified: ").append(toIndentedString(isVerified)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
