/*
 * investor
 * This swagger documentation provides investor onboarding api details.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.investor.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** StockValue */
@JsonPropertyOrder({StockValue.JSON_PROPERTY_STOCK_NAME, StockValue.JSON_PROPERTY_VALUE})
@JsonTypeName("stockValue")
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2020-10-03T17:43:44.473+05:30[Asia/Kolkata]")
public class StockValue {
  public static final String JSON_PROPERTY_STOCK_NAME = "stockName";
  private String stockName;

  public static final String JSON_PROPERTY_VALUE = "value";
  private InvestorRoles value;

  public StockValue stockName(String stockName) {

    this.stockName = stockName;
    return this;
  }

  /**
   * Get stockName
   *
   * @return stockName
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STOCK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStockName() {
    return stockName;
  }

  public void setStockName(String stockName) {
    this.stockName = stockName;
  }

  public StockValue value(InvestorRoles value) {

    this.value = value;
    return this;
  }

  /**
   * Get value
   *
   * @return value
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public InvestorRoles getValue() {
    return value;
  }

  public void setValue(InvestorRoles value) {
    this.value = value;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StockValue stockValue = (StockValue) o;
    return Objects.equals(this.stockName, stockValue.stockName)
        && Objects.equals(this.value, stockValue.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stockName, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StockValue {\n");
    sb.append("    stockName: ").append(toIndentedString(stockName)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
